apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: spring-petclinic-db
  annotations:
    kapp.k14s.io/identity: v1;dev-tap/carto.run/Workload/spring-petclinic;carto.run/v1alpha1
    kapp.k14s.io/original: '{"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"labels":{"app.kubernetes.io/part-of":"spring-petclinic","apps.tanzu.vmware.com/nopr":"true","apps.tanzu.vmware.com/workload-type":"web","kapp.k14s.io/app":"1655842000127906348","kapp.k14s.io/association":"v1.fb16eb8b0aed4a10933813c2bf86255f","tanzu.app.live.view":"true","tanzu.app.live.view.application.name":"spring-petclinic"},"name":"spring-petclinic","namespace":"dev-tap"},"spec":{"env":[{"name":"SPRING_PROFILES_ACTIVE","value":"postgres"}],"params":[{"name":"annotations","value":{"autoscaling.knative.dev/minScale":"1"}},{"name":"gitops_repository","value":"https://github.com/warroyo/tap-gitops"},{"name":"gitops_branch","value":"main"}],"serviceClaims":[{"name":"db","ref":{"apiVersion":"services.apps.tanzu.vmware.com/v1alpha1","kind":"ResourceClaim","name":"ack-rds-claim"}}],"source":{"git":{"ref":{"branch":"main","tag":"tap-1.2"},"url":"https://github.com/warroyo/spring-petclinic"}}}}'
    kapp.k14s.io/original-diff-md5: c6e94dc94aed3401b5d0f26ed6c0bff3
    autoscaling.knative.dev/minScale: "1"
  labels:
    app.kubernetes.io/part-of: spring-petclinic
    apps.tanzu.vmware.com/nopr: "true"
    apps.tanzu.vmware.com/workload-type: web
    kapp.k14s.io/app: "1655842000127906348"
    kapp.k14s.io/association: v1.fb16eb8b0aed4a10933813c2bf86255f
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.name: spring-petclinic
    app.kubernetes.io/component: run
    carto.run/workload-name: spring-petclinic
spec:
  name: db
  service:
    apiVersion: services.apps.tanzu.vmware.com/v1alpha1
    kind: ResourceClaim
    name: ack-rds-claim
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: spring-petclinic

