apiVersion: kapp.k14s.io/v1alpha1
kind: Config
waitRules:
- conditionMatchers:
  - type: ServiceAvailable
    status: "False"
    failure: true
  - type: ServiceAvailable
    status: "True"
    success: true
  resourceMatchers:
  - apiVersionKindMatcher:
      apiVersion: servicebinding.io/v1alpha3
      kind: ServiceBinding
---
apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: spring-petclinic-db
  annotations:
    kapp.k14s.io/identity: v1;dev-tap/carto.run/Workload/spring-petclinic;carto.run/v1alpha1
    autoscaling.knative.dev/minScale: "1"
  labels:
    app.kubernetes.io/part-of: spring-petclinic
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    kapp.k14s.io/app: "1655842000127906348"
    kapp.k14s.io/association: v1.fb16eb8b0aed4a10933813c2bf86255f
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.name: spring-petclinic
    app.kubernetes.io/component: run
    carto.run/workload-name: spring-petclinic
spec:
  name: db
  service:
    apiVersion: services.apps.tanzu.vmware.com/v1alpha1
    kind: ResourceClaim
    name: ack-rds-claim
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: spring-petclinic

