apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  creationTimestamp: "2022-08-22T21:30:03Z"
  generation: 1
  labels:
    app.kubernetes.io/component: deliverable
    app.kubernetes.io/part-of: tanzu-java-web-app
    app.tanzu.vmware.com/deliverable-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    carto.run/cluster-template-name: deliverable-template
    carto.run/resource-name: deliverable
    carto.run/supply-chain-name: source-test-scan-to-url
    carto.run/template-kind: ClusterTemplate
    carto.run/workload-name: tanzu-java-web-app
    carto.run/workload-namespace: dev-tap
    kapp.k14s.io/app: "1655842000127906348"
    kapp.k14s.io/association: v1.649ae3074ef84e45d7edc6eaf487b073
    testlabel: test
  name: tanzu-java-web-app
  namespace: default
  resourceVersion: "69814423"
  uid: d9922851-5b19-4500-8c91-cc45ffa8f6d1
spec:
  params:
  - name: gitops_ssh_secret
    value: github-warroyo-secret
  - name: gitops_sub_path
    value: config/dev-tap/tanzu-java-web-app
  source:
    git:
      ref:
        branch: main
      url: https://github.com/warroyo/tap-gitops.git
