apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  labels:
    app.kubernetes.io/component: deliverable
    app.kubernetes.io/part-of: spring-sensors
    app.tanzu.vmware.com/deliverable-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    carto.run/cluster-template-name: deliverable-template
    carto.run/resource-name: deliverable
    carto.run/supply-chain-name: source-test-scan-to-url
    carto.run/template-kind: ClusterTemplate
    carto.run/workload-name: spring-sensors
    carto.run/workload-namespace: dev-tap
  name: spring-sensors
  namespace: default
spec:
  params:
  - name: gitops_ssh_secret
    value: github-warroyo-secret
  source:
    subPath: /config/dev-tap/spring-sensors
    git:
      ref:
        branch: main
      url: https://github.com/warroyo/tap-gitops.git
