apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: steeltoe-weather
  namespace: dev-tap
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: steeltoe-weather
    tanzu.app.live.view: "true"
    apps.tanzu.vmware.com/has-tests: "true"
    tanzu.app.live.view.application.flavours: steeltoe
    tanzu.app.live.view.application.name: steeltoe-weatherforecast
spec:
  source:
    git:
      url: https://github.com/sample-accelerators/steeltoe-weatherforecast
      ref:
        branch: tap-1.1
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: gitops_repository
      value: https://github.com/warroyo/tap-gitops
    - name: gitops_branch
      value: main
