apiVersion: apis.apps.tanzu.vmware.com/v1alpha1
kind: APIDescriptor
metadata:
  name: company-api-flux
  annotations:
    kapp.k14s.io/identity: v1;dev-tap/carto.run/Workload/company-api-flux;carto.run/v1alpha1
    kapp.k14s.io/original: '{"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"labels":{"apis.apps.tanzu.vmware.com/register-api":"true","app.kubernetes.io/part-of":"company-api-flux","apps.tanzu.vmware.com/has-tests":"true","apps.tanzu.vmware.com/workload-type":"web","kapp.k14s.io/app":"1655842000127906348","kapp.k14s.io/association":"v1.362c820049d5da3ba00f14bc6527da2f"},"name":"company-api-flux","namespace":"dev-tap"},"spec":{"build":{"env":[{"name":"BP_KEEP_FILES","value":"docs/*"}]},"params":[{"name":"api_descriptor","value":{"description":"api for company app","location":{"path":"/docs/openapi.json"},"owner":"default","system":"test-installation","type":"openapi"}}],"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/warroyo/tap-go-sample"}}}}'
    kapp.k14s.io/original-diff-md5: c6e94dc94aed3401b5d0f26ed6c0bff3
  labels:
    apis.apps.tanzu.vmware.com/register-api: "true"
    app.kubernetes.io/part-of: company-api-flux
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    kapp.k14s.io/app: "1655842000127906348"
    kapp.k14s.io/association: v1.362c820049d5da3ba00f14bc6527da2f
    app.kubernetes.io/component: run
    carto.run/workload-name: company-api-flux
spec:
  type: openapi
  description: api for company app
  system: test-installation
  owner: default
  location:
    path: /docs/openapi.json
    baseURL:
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: company-api-flux

