apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: company-api
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    apis.apps.tanzu.vmware.com/register-api: "true"
    app.kubernetes.io/part-of: company-api
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    kapp.k14s.io/app: "1655842000127906348"
    kapp.k14s.io/association: v1.57af1f31a037d7305e43032152ae1545
    app.kubernetes.io/component: run
    carto.run/workload-name: company-api
spec:
  template:
    metadata:
      annotations:
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
        kapp.k14s.io/identity: v1;dev-tap/carto.run/Workload/company-api;carto.run/v1alpha1
        kapp.k14s.io/original: '{"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"labels":{"apis.apps.tanzu.vmware.com/register-api":"true","app.kubernetes.io/part-of":"company-api","apps.tanzu.vmware.com/has-tests":"true","apps.tanzu.vmware.com/workload-type":"web","kapp.k14s.io/app":"1655842000127906348","kapp.k14s.io/association":"v1.57af1f31a037d7305e43032152ae1545"},"name":"company-api","namespace":"dev-tap"},"spec":{"build":{"env":[{"name":"BP_KEEP_FILES","value":"docs/*"}]},"params":[{"name":"api_descriptor","value":{"description":"api for company app","location":{"path":"/docs/openapi.json"},"owner":"default","system":"test-installation","type":"openapi"}}],"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/warroyo/tap-go-sample"}}}}'
        kapp.k14s.io/original-diff-md5: c6e94dc94aed3401b5d0f26ed6c0bff3
      labels:
        apis.apps.tanzu.vmware.com/register-api: "true"
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: company-api
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: company-api
        kapp.k14s.io/app: "1655842000127906348"
        kapp.k14s.io/association: v1.57af1f31a037d7305e43032152ae1545
    spec:
      containers:
      - image: dev.registry.pivotal.io/warroyo/supply-chain/company-api-dev-tap@sha256:f7f409d4c2468f40d7f5bac1f4a0d47450c7b6f7c0489800b45493575813f76f
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

