apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  creationTimestamp: "2022-12-22T17:52:40Z"
  generation: 1
  labels:
    apis.apps.tanzu.vmware.com/register-api: "true"
    app.kubernetes.io/component: deliverable
    app.kubernetes.io/part-of: company-api
    app.tanzu.vmware.com/deliverable-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    carto.run/cluster-template-name: deliverable-template
    carto.run/resource-name: deliverable
    carto.run/supply-chain-name: source-test-scan-to-url
    carto.run/template-kind: ClusterTemplate
    carto.run/workload-name: company-api
    carto.run/workload-namespace: dev-tap
    kapp.k14s.io/app: "1655842000127906348"
    kapp.k14s.io/association: v1.57af1f31a037d7305e43032152ae1545
  name: company-api
  namespace: default
spec:
  params:
  - name: gitops_ssh_secret
    value: github-warroyo-secret
  source:
    git:
      ref:
        branch: main
      url: https://github.com/warroyo/tap-gitops.git
    subPath: config/dev-tap/company-api
