
apiVersion: v1
kind: Service
metadata:
  name: java-harness-lb
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/part-of: java-harness
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
