apiVersion: networking.istio.io/v1alpha3  
kind: VirtualService  
metadata:  
  annotations:  
    harness.io/managed: "true"  
  name: {{.Values.name}}-virtualservice  
spec:  
  gateways:  
  - {{.Values.name}}-gateway  
  hosts:  
  - '*' 
  http:  
  - route:  
    - destination:  
        host: {{.Values.name}}
