apiVersion: apps/v1
kind: Deployment
metadata:
  name: company-api-server
  annotations:
    kapp.k14s.io/update-strategy: fallback-on-replace
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    apis.apps.tanzu.vmware.com/register-api: "true"
    app.kubernetes.io/part-of: company-api-server
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/component: run
    carto.run/workload-name: company-api-server
spec:
  selector:
    matchLabels:
      apis.apps.tanzu.vmware.com/register-api: "true"
      app.kubernetes.io/component: run
      app.kubernetes.io/part-of: company-api-server
      apps.tanzu.vmware.com/has-tests: "true"
      apps.tanzu.vmware.com/workload-type: server
      carto.run/workload-name: company-api-server
  template:
    metadata:
      annotations:
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
        kapp.k14s.io/identity: v1;dev-tap/carto.run/Workload/company-api-server;carto.run/v1alpha1
        kapp.k14s.io/original: '{"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"labels":{"apis.apps.tanzu.vmware.com/register-api":"true","app.kubernetes.io/part-of":"company-api-server","apps.tanzu.vmware.com/has-tests":"true","apps.tanzu.vmware.com/workload-type":"server","kapp.k14s.io/app":"1655842000127906348","kapp.k14s.io/association":"v1.1ad6cc3376109ad896268f73eebc23a0"},"name":"company-api-server","namespace":"dev-tap"},"spec":{"build":{"env":[{"name":"BP_KEEP_FILES","value":"docs/*"}]},"params":[{"name":"api_descriptor","value":{"description":"api for company app","location":{"path":"/docs/openapi.json"},"owner":"default","system":"test-installation-test","type":"openapi"}}],"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/warroyo/tap-go-sample"}}}}'
        kapp.k14s.io/original-diff-md5: c6e94dc94aed3401b5d0f26ed6c0bff3
      labels:
        apis.apps.tanzu.vmware.com/register-api: "true"
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: company-api-server
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: server
        carto.run/workload-name: company-api-server
    spec:
      containers:
      - image: dev.registry.pivotal.io/warroyo/supply-chain/company-api-server-dev-tap@sha256:562b22e10fdd1297e56e4a87e8dd3a832e776e54cc04772ca842bc2ceaef41e5
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default
---
apiVersion: v1
kind: Service
metadata:
  name: company-api-server
  labels:
    apis.apps.tanzu.vmware.com/register-api: "true"
    app.kubernetes.io/part-of: company-api-server
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/component: run
    carto.run/workload-name: company-api-server
spec:
  selector:
    apis.apps.tanzu.vmware.com/register-api: "true"
    app.kubernetes.io/component: run
    app.kubernetes.io/part-of: company-api-server
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: server
    carto.run/workload-name: company-api-server
  ports:
  - targetPort: 8080
    port: 8080
    name: http

